/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Farrel
 */
public class Managerv2 extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    // Variabel global untuk koneksi dan statement
    private Connection conn;
    private Statement stmt;
    public Managerv2() {
        initComponents();
        initDatabase();
        tampilkanDataKamar();
    }
    
    
     private void initDatabase() {
        try {
            conn = Database.getConnection();
            stmt = conn.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi ke database: " + e.getMessage());
        }
    }
    
    
   private void tampilkanDataKamar() {
    DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "No Kamar", "Status"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Hanya kolom No Kamar (index 1) yang bisa diubah
            return column == 1;
        }
    };

    try {
        // Ambil idKamar, no_kamar, dan status dari database
        ResultSet rs = stmt.executeQuery("SELECT idKamar, no_kamar, status FROM kamar");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("idKamar"),
                rs.getString("no_kamar"),
                rs.getString("status")
            });
        }

        tabel_kamar.setModel(model);

        // Listener untuk perubahan data tabel
        model.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();

            if (column == 1) { // Kolom No Kamar diubah
                int id = (int) model.getValueAt(row, 0);
                String newNoKamar = model.getValueAt(row, 1).toString();

                try {
                    String sql = "UPDATE kamar SET no_kamar = '" + newNoKamar + "' WHERE idKamar = " + id;
                    int result = stmt.executeUpdate(sql);
                    if (result > 0) {
                        System.out.println("Data kamar berhasil diubah.");
                    } else {
                        System.out.println("Gagal mengubah data kamar.");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error update data: " + ex.getMessage());
                }
            }
        });

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kamar = new javax.swing.JTable();
        input_carikamar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_carikamar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        side_datakamar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_tambahkamar = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Manajemen Data Kamar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        tabel_kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"101", "King Bed", "Standard", "Rp 300.000"},
                {"102", "Twin Bed", "Standard", "Rp 300.000"},
                {"103", "Queen Bed", "Standard", "Rp 300.000"},
                {"201", "King Bed", "Predisent Suite", "Rp 1.500.000"},
                {"202", "King Bed", "Predisent Suite", "Rp 1.500.000"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Kamar", "Tipe", "Kelas", "Harga"
            }
        ));
        tabel_kamar.setShowGrid(false);
        tabel_kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kamarMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabel_kamarMouseReleased(evt);
            }
        });
        tabel_kamar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tabel_kamarInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kamar);

        input_carikamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_carikamarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nomor kamar :");

        btn_carikamar.setText("Cari");
        btn_carikamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carikamarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        side_datakamar.setText("Data Kamar");
        side_datakamar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        side_datakamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side_datakamarActionPerformed(evt);
            }
        });

        jButton2.setText("Dashboard");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(side_datakamar, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(side_datakamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_tambahkamar.setBackground(new java.awt.Color(0, 102, 102));
        btn_tambahkamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/image/more.png"))); // NOI18N
        btn_tambahkamar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tambahkamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahkamarActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(0, 102, 102));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/image/edit.png"))); // NOI18N
        btn_edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(0, 102, 102));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/image/delete.png"))); // NOI18N
        btn_hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_carikamar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_carikamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tambahkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_tambahkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(input_carikamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_carikamar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_carikamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_carikamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_carikamarActionPerformed

    private void btn_carikamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carikamarActionPerformed
        // TODO add your handling code here:
        // Ambil input nomor kamar dari textfield
         String keyword = input_carikamar.getText().trim();
    if (keyword.isEmpty()) {
        tampilkanDataKamar();
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tabel_kamar.getModel();
    model.setRowCount(0);

    try {
        String sql = "SELECT * FROM kamar WHERE no_kamar LIKE '%" + keyword + "%'";
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            Object[] row = {
                rs.getInt("idKamar"),
                rs.getString("no_kamar")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mencari data kamar: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_carikamarActionPerformed

    private void side_datakamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side_datakamarActionPerformed
        // TODO add your handling code here:
        Managerv2 ManagerFrame = new Managerv2();
    ManagerFrame.setVisible(true);

    // Tutup form saat ini (opsional)
    this.dispose();
        
    }//GEN-LAST:event_side_datakamarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashboardManagerUi reservasiFrame = new DashboardManagerUi();
        reservasiFrame.setVisible(true);

    // Tutup form saat ini (opsional)
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_kamarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabel_kamarInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_kamarInputMethodTextChanged

    private void btn_tambahkamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahkamarActionPerformed
        // TODO add your handling code here:
         String noKamar = JOptionPane.showInputDialog(this, "Masukkan nomor kamar:");
    if (noKamar != null && !noKamar.trim().isEmpty()) {
        try {
            String sql = "INSERT INTO kamar (no_kamar) VALUES ('" + noKamar.trim() + "')";
            int result = stmt.executeUpdate(sql);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Kamar berhasil ditambahkan.");
                tampilkanDataKamar();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan kamar.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_tambahkamarActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_kamar.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih kamar yang ingin diedit.");
        return;
    }

    int id = (int) tabel_kamar.getValueAt(selectedRow, 0);
    String currentNoKamar = tabel_kamar.getValueAt(selectedRow, 1).toString();
    String newNoKamar = JOptionPane.showInputDialog(this, "Edit Nomor Kamar:", currentNoKamar);

    if (newNoKamar != null && !newNoKamar.trim().isEmpty()) {
        try {
            String sql = "UPDATE kamar SET no_kamar = '" + newNoKamar.trim() + "' WHERE idKamar = " + id;
            int result = stmt.executeUpdate(sql);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Nomor kamar berhasil diperbarui.");
                tampilkanDataKamar();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui nomor kamar.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat update: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_kamar.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih kamar yang ingin dihapus.");
        return;
    }

    int id = (int) tabel_kamar.getValueAt(selectedRow, 0);
    int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kamar ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM kamar WHERE idKamar = " + id;
            int result = stmt.executeUpdate(sql);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Kamar berhasil dihapus.");
                tampilkanDataKamar();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus kamar.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat menghapus kamar: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabel_kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kamarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_kamarMouseClicked

    private void tabel_kamarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kamarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_kamarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managerv2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_carikamar;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambahkamar;
    private javax.swing.JTextField input_carikamar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton side_datakamar;
    private javax.swing.JTable tabel_kamar;
    // End of variables declaration//GEN-END:variables
}
