/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;



/**
 *
 * @author Farrell
 */
public class Restoran extends javax.swing.JFrame {

    private TamuClass tamuClass = new TamuClass();
    private Menu menu = new Menu();
    private ArrayList<Object[]> pesanan = new ArrayList<>();

    /**
     * Creates new form Restoran
     */
    public Restoran() {
        initComponents();
        isiComboBoxTamu();
        tampilkanDataMenu();

        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID Menu", "Nama", "Harga", "Qty"}, 0);
table_pesanan.setModel(model);

// Sembunyikan kolom ID Menu
table_pesanan.getColumnModel().getColumn(0).setMinWidth(0);
table_pesanan.getColumnModel().getColumn(0).setMaxWidth(0);
table_pesanan.getColumnModel().getColumn(0).setWidth(0);



    }


    
    private void isiComboBoxTamu() {
    try {
        input_tamu.removeAllItems();
        List<ItemCombo> daftarTamu = tamuClass.getAllTamu();
        for (ItemCombo item : daftarTamu) {
            input_tamu.addItem(item);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data tamu: " + e.getMessage());
    }
}

private int ambilIdTamu() {
    ItemCombo selected = (ItemCombo) input_tamu.getSelectedItem();
    return selected != null ? selected.getId() : -1;
}


private void tampilkanDataMenu() {
    DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nama", "Harga"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 1 || column == 2;
        }
    };

    // Ambil data dari class TamuClass
    for (Object[] row : menu.getDataMenu()) {
        model.addRow(row);
    }

    table_makanan.setModel(model);

    model.addTableModelListener(e -> {
        int row = e.getFirstRow();
        int column = e.getColumn();

        if (column == 1) {
            int id = (int) model.getValueAt(row, 0);
            String newNama = model.getValueAt(row, 1).toString();
            int harga = (int) model.getValueAt(row, 2);


            boolean updated = menu.updateDataMenu(id, newNama, harga);
            if (updated) {
                System.out.println("Data tamu berhasil diubah.");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data menu.");
            }
        }
    });
}


private void hitungTotalHarga() {
    DefaultTableModel model = (DefaultTableModel) table_pesanan.getModel();
    int total = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        int harga = (int) model.getValueAt(i, 2);
        int qty = (int) model.getValueAt(i, 3);
        total += harga * qty;
    }

    total_harga.setText("Rp " + total);
}






 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_makanan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        input_jumlah = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_pesanan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_bayar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        input_tamu = new javax.swing.JComboBox<>();
        btn_tambah_menu = new javax.swing.JButton();
        btn_hapus_menu = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        total_harga = new javax.swing.JTextField();
        btn_hapuspesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_makanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "Harga"
            }
        ));
        table_makanan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(table_makanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 366, 373));

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(627, 86));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU RESTORAN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(177, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(177, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(177, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 623, -1));
        getContentPane().add(input_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 132, 170, -1));

        jLabel3.setText("Jumlah :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 110, 51, -1));

        jLabel4.setText("Semua Pesanan :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 191, 99, -1));

        table_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Harga", "Qty"
            }
        ));
        jScrollPane2.setViewportView(table_pesanan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 213, 236, 201));

        jLabel5.setText("Total Harga :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 423, 81, -1));

        btn_bayar.setBackground(new java.awt.Color(51, 102, 255));
        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 495, 236, -1));

        jLabel6.setText("Tamu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 113, -1, -1));

        input_tamu.setBackground(new java.awt.Color(204, 204, 204));
        input_tamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tamuActionPerformed(evt);
            }
        });
        getContentPane().add(input_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 110, 149, -1));

        btn_tambah_menu.setBackground(new java.awt.Color(153, 255, 153));
        btn_tambah_menu.setText("Tambah Menu");
        btn_tambah_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 110, -1, -1));

        btn_hapus_menu.setBackground(new java.awt.Color(255, 51, 51));
        btn_hapus_menu.setText("Hapus");
        btn_hapus_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        btn_tambah.setBackground(new java.awt.Color(153, 255, 153));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 160, -1, -1));

        total_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(total_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 455, 236, 28));

        btn_hapuspesanan.setBackground(new java.awt.Color(255, 51, 51));
        btn_hapuspesanan.setText("Hapus");
        btn_hapuspesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapuspesananActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapuspesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                         

    private void input_tamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tamuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_input_tamuActionPerformed

    private void btn_tambah_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_menuActionPerformed
    JTextField inputNama = new JTextField();
    JTextField inputHarga = new JTextField();

    Object[] message = {
        "Nama Menu:", inputNama,
        "Harga:", inputHarga
    };

    int option = JOptionPane.showConfirmDialog(this, message, "Tambah Menu", JOptionPane.OK_CANCEL_OPTION);
    if (option == JOptionPane.OK_OPTION) {
        try {
            String nama = inputNama.getText();
            int harga = Integer.parseInt(inputHarga.getText());

            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama menu tidak boleh kosong.");
                return;
            }

            boolean success = menu.insertDataMenu(nama, harga);
            if (success) {
                JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan.");
                tampilkanDataMenu(); // Refresh tabel
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan menu.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
        }
    }
}                                               
//GEN-LAST:event_btn_tambah_menuActionPerformed

    

    private void btn_hapus_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_menuActionPerformed
    int selectedRow = table_makanan.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih menu yang ingin dihapus terlebih dahulu.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus menu ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        int id = (int) table_makanan.getValueAt(selectedRow, 0);

        boolean success = menu.hapusDataMenu(id);
        if (success) {
            JOptionPane.showMessageDialog(this, "Menu berhasil dihapus.");
            tampilkanDataMenu(); // Refresh tabel
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus menu.");
        }
    }
}//GEN-LAST:event_btn_hapus_menuActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed

   int selectedRow = table_makanan.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih makanan terlebih dahulu!");
        return;
    }

    int idMenu = (int) table_makanan.getValueAt(selectedRow, 0);  // Ambil ID Menu dari kolom 0
    String nama = table_makanan.getValueAt(selectedRow, 1).toString();
    int harga = (int) table_makanan.getValueAt(selectedRow, 2);
    int qty = (int) input_jumlah.getValue();

    if (qty <= 0) {
        JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0!");
        return;
    }

    // Tambah ke tabel pesanan (UI)
    DefaultTableModel model = (DefaultTableModel) table_pesanan.getModel();
    model.addRow(new Object[]{idMenu, nama, harga, qty});

    // Tambah ke arraylist pesanan untuk disimpan ke database
    pesanan.add(new Object[]{idMenu, nama, harga, qty});

    hitungTotalHarga();
}//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapuspesananActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        int selectedRow = table_pesanan.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih pesanan yang ingin dihapus!");
        return;
    }

    // Hapus dari tabel
    DefaultTableModel model = (DefaultTableModel) table_pesanan.getModel();
    model.removeRow(selectedRow);

    // Hapus juga dari ArrayList pesanan
    if (selectedRow < pesanan.size()) {
        pesanan.remove(selectedRow);
    }

    // Hitung ulang total
    hitungTotalHarga();
    }

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {                                          
       ItemCombo selectedTamu = (ItemCombo) input_tamu.getSelectedItem();
    if (selectedTamu == null) {
        JOptionPane.showMessageDialog(this, "Pilih tamu terlebih dahulu.");
        return;
    }

    int idTamu = selectedTamu.getId();
    int totalHarga = 0;

    for (Object[] item : pesanan) {
        int harga = (int) item[2];
        int qty = (int) item[3];
        totalHarga += harga * qty;
    }

    boolean berhasil = menu.insertTransaksi(idTamu, totalHarga, pesanan);
    if (berhasil) {
        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
        pesanan.clear();
        ((DefaultTableModel) table_pesanan.getModel()).setRowCount(0);
        total_harga.setText("Rp 0");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi.");
    }
    }                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_hapus_menu;
    private javax.swing.JButton btn_hapuspesanan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah_menu;
    private javax.swing.JSpinner input_jumlah;
    private javax.swing.JComboBox<ItemCombo> input_tamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_makanan;
    private javax.swing.JTable table_pesanan;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
}
